app/mod_auth/routes.py
#flask dependencies
from flask import Flask, render_template, redirect, url_for, Blueprint, request, session
import flask
from flask_wtf import FlaskForm 
from app.mod_auth.forms import RegisterForm, LoginForm, AppraisalForm, MitigationForm
from flask_sqlalchemy  import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from sqlalchemy.exc import IntegrityError
import numpy as np
import csv
import math
from plotly.offline import plot
from plotly.graph_objs import Scatter
import plotly.graph_objs as go

from riskpy.vulnerability import vulnerability as vul
#import database object from app module 
from app import db, login_manager
from datetime import datetime
from app import app
#Import module models containing User
from app.mod_auth.models import User

#Define the blueprint: 'auth', sets its url prefix: app.url/auth
mod = Blueprint('mod_auth', __name__, url_prefix = "/auth")

def rating (damage):
    if damage[4] < 15000 and damage[5] < 40000:
        return 1
    elif damage[3] < 15000 and damage[4] < 40000:
        return 2
    elif damage[2] < 20000 and damage[3] < 30000:
        return 3
    else:
        return 4


def search(zipcode):
    with open('app/mod_auth/Zip_MedianValuePerSqft.csv', 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            if row["RegionName"] == str(zipcode):
                return row["2018-01"]


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

#set route and accepted methods
@mod.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('mod_auth.dashboardcustomer'))
        return '<h1>Invalid username or password</h1>'
    return render_template('auth/login.html', form=form)

@mod.route('/loginguest', methods=['POST'])
def loginguest():
    if request.method == 'POST' and request.form["guest"] == "guest":
        user = User.query.filter_by(email="guest@email.com").first()
        if user:
            if check_password_hash(user.password, "guestPass123"):
                login_user(user)
                return redirect(url_for('mod_auth.dashboardcustomer'))
        return '<h1>Invalid username or password</h1>'
    return render_template('auth/login.html', form=form) 


@mod.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        try:
            new_user = User(email=form.email.data, password=hashed_password)
            #check if email is taken
            #user = User.query.filter_by(email=form.email.data).first()
            db.session.add(new_user)
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            return '<h1>This email address is already taken.</h1>'
        return redirect(url_for('mod_auth.login'))
    return render_template('auth/signup.html', form=form)
"""
@mod.route('/dashboard')
@login_required
def dashboard():
    return render_template('auth/dashboard.html', name=current_user.first_name)
"""
@mod.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))


@mod.route('/dashboardcustomer', methods=['GET', 'POST'])
@login_required
def dashboardcustomer():
    form = AppraisalForm()
    
    if form.is_submitted():
        print ("submitted")
        print(form.errors)

    if form.validate_on_submit():
        print("validated")
        params_object = {
            "year": form.year.data,
            "zip_code": form.zip_code.data,
            "area": form.area.data,
            "window_protection": form.window_protection.data,
            "surroundings": form.surroundings.data,
            "last_roof_renew": form.last_roof_renew.data,
            "roof_wall_connection": form.roof_wall_connection.data,
            "type_of_roof_cover": form.type_of_roof_cover.data,
            "type_of_construction": form.type_of_construction.data,
            "type_of_roof_sheathing": form.type_of_roof_sheathing.data,
            "type_of_windows": form.type_of_windows.data
        }

        value_est = int(search(params_object["zip_code"]))
        area = int(params_object["area"]) * 0.09290
        base_side = math.sqrt(area/2)
        cap_window = None

        if params_object["type_of_windows"] == "d":
            cap_window = 3330
        else:
            cap_window = int(params_object["type_of_windows"])
 
        if params_object["window_protection"] == "True":
            cap_window = 6300


        lenght = 2 * base_side
        width = base_side
        exp_cat = params_object["surroundings"]
        gust_speed = np.arange(0, 120)  # m/s
        
        #walls capacity
        cap_walls = 2614
        if int(params_object["type_of_construction"]) == 6300:
            cap_walls = int(params_object["type_of_construction"])
        else:
            if int(params_object["year"]) < 1991:
                cap_walls = 2614
            elif int(params_object["year"]) < 2001:
                cap_walls = 4932
            else:
                cap_walls = 6300

       
        cap_r2w = 1900
        if params_object["roof_wall_connection"] == "d":
            if int(params_object["year"]) < 1991:
                cap_r2w = 1846
            elif int(params_object["year"]) < 2001:
                cap_r2w = 3069
            else:
                cap_r2w = 5840
        else:
            cap_r2w = int(params_object["roof_wall_connection"])

        cap_rs = 2614
        if params_object["type_of_roof_sheathing"] == "d":
            if int(params_object["year"]) < 1991:
                cap_rs = 2614
            elif int(params_object["year"]) < 2001:
                cap_rs = 4932
            else:
                cap_rs = 6300
        else:
            cap_rs = int(params_object["type_of_roof_sheathing"])

        cap_door = 2394
        if int(params_object["year"]) < 2005:
            cap_door = 2394
        else:
            cap_door = 4788

        cap_gd = 1500
        if int(params_object["year"]) < 2005:
            cap_gd = 1430
        else:
            cap_gd = 2490


        cap_rc = 2442
        if params_object["type_of_roof_cover"] == "d":
            if int(params_object["year"]) < 1991:
                cap_rw2 = 2442
            else:
                cap_rc = 3352
        else:
            cap_rc = int(params_object["type_of_roof_cover"])

        wall_height = 3
        roof_height = 4
        n_windows = 10
        cov = 0.5
        year = datetime.utcnow().year
        if (int(params_object["last_roof_renew"])  - year) > 7:
            cap_rc = cap_rc * 0.8
            cap_rs = cap_rs * 0.8
            cap_r2w = cap_r2w * 0.8

        # ------------------ Main Function Vulnerability Estimation ------------------
        damage_ration = vul.vulnerability(exp_cat=exp_cat, gust_speed=gust_speed, cap_walls=cap_walls,
                            cap_rc=cap_rc, cap_rs=cap_rs, cap_window=cap_window, cap_door=cap_door,
                            cap_gd=cap_gd, lenght=lenght, width=width, cov=cov, wall_height=3,
                            roof_height=4, n_windows=10) 
        dollar_damage = damage_ration * int(value_est) * int(params_object["area"])

        print(dollar_damage)

        calculated_params = {
            "exp_cat": exp_cat, 
            "gust_speed": 0, 
            "cap_walls": cap_walls,
            "cap_rc": cap_rc, 
            "cap_rs": cap_rs, 
            "cap_window": cap_window, 
            "cap_door": cap_door,
            "cap_gd": cap_gd, 
            "lenght": lenght, 
            "width": width, 
            "cov": cov, 
            "cap_r2w": cap_r2w,
            "wall_height": 3,
            "roof_height": 4, 
            "n_windows": 10
        }
        new_arr =tuple(damage_ration)
        session['dollar_damage'] = tuple(dollar_damage)
        session['params_object'] = params_object
        session['calculated_params'] = calculated_params
        session['damage_ration'] = new_arr
        session['value_est'] = value_est
        return redirect(url_for('mod_auth.estimation'))

    return render_template('customer/dashboard_customer.html', name=current_user.email, form=form)

@mod.route('/estimation', methods=['GET', 'POST'])
@login_required
def estimation():
    damage_ration = session.pop('damage_ration', None)
    dollar_damage = session.pop('dollar_damage', None)
    value_est = session.pop('value_est', None)
    params_object = session.pop('params_object', None)
    session["dollar_damage"] = dollar_damage
    session["damage_ration"] = damage_ration
    session["value_est"] = value_est
    session["params_object"] = params_object
    gust_speed = np.arange(0, 120)  # m/s
    dollar_damage= np.array(dollar_damage)
    dollar_damage = dollar_damage - dollar_damage[0]
    my_plot_div = plot([Scatter(x=gust_speed * 2.237, y= dollar_damage)], output_type='div')
    damage_cats = [dollar_damage[30], dollar_damage[40], dollar_damage[48], dollar_damage[57], dollar_damage[65], dollar_damage[78]]
    damage_cats = [round(a/1000)*1000 for a in damage_cats]
    rate = rating(damage_cats)
    return render_template('customer/estimation.html', value = value_est * int(params_object["area"]) , div_placeholder= flask.Markup(my_plot_div), dollar_damage = damage_cats, rate = rate)

@mod.route('/mitigation', methods=['GET', 'POST'])
@login_required
def mitigation():
    form = MitigationForm()

    if form.validate_on_submit():
        mitigation_params = {
            "window_protection": form.window_protection.data,

app/templates/customer/dashboard_customer.html
<!-- Author Daniel Bis -->
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}
Dashboard


{% endblock %}

{% block styles %}
{{super()}}
<style type="text/css">
  .myCarousel {
    
    text-align: right;
    margin-left: 40px;
  }
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 100%;
      margin: auto;

  }

  .logo {
    position: relative;,
    top: 0;
    left: 0;
  }
  body {
    background-color: white; 
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    color: #fff !important;
    font-size: 16px;

  }

</style>
{% endblock %}



{% block content %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">storm-risk</a>
        </div>
      </div>
    </nav>

    <div class="container-fluid" style="color: black;">
      <div class="row" style="margin-top: 60px">
        <div class="col-md-6" style = "text-align: center; margin-top: 20px background-color: black">
          
          <div class="row" style="margin-top: 40px">
          <div class="col-md-4" style="text-align: left;"> 
              <img class = "logo" src="{{ url_for('static', filename='logo.jpg') }}" width="100%" height="100%">
          </div>
          <div class="col-md-8" style="margin-top: 60px;">
            <p > We are here to prevent, not respond. Don't let hurricane suprise you, check your potential loses, find vulnerabilities and fix them. <br> Protect your home and family.</p>
          </div>
          </div>

          <div id="myCarousel" class="carousel slide" data-ride="carousel" s>
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">

              <div class="item active">
                <img src="{{ url_for('static', filename='hurr_mid.jpg') }}" width="460" height="415">
              </div>

              <div class="item">
                <img src="{{ url_for('static', filename='tornado_mid.jpg') }}" width="460" height="415">

              </div>
            
              <div class="item">
                <img src="{{ url_for('static', filename='hr_mid.jpg') }}" width="460" height="415">
              </div> 
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
      </div>


        <div class="col-md-6" style = "text-align: left; background: #fff margin-left: 0" >
            <form class="form-appraisal" method="POST", action="/auth/dashboardcustomer">
            <h2 class="form-appraisal-heading">Please provide your house characteristics</h2>
            {{ form.hidden_tag() }}
            {{ wtf.form_field(form.year) }}
            {{ wtf.form_field(form.zip_code) }}
            {{ wtf.form_field(form.area) }}
            {{ wtf.form_field(form.window_protection) }}
            {{ wtf.form_field(form.surroundings) }}
            {{ wtf.form_field(form.last_roof_renew) }}
            <p class="form-appraisal-advanced">Options below are optional, but will make the estimate more accurate.</p>
            {{ wtf.form_field(form.roof_wall_connection) }}
            {{ wtf.form_field(form.type_of_roof_cover) }}
            {{ wtf.form_field(form.type_of_roof_sheathing) }}
            {{ wtf.form_field(form.type_of_construction) }}
            {{ wtf.form_field(form.type_of_windows) }}
            <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
            </form>
        </div>
        
    </div>
    
    </div>




{% endblock %}

app/templates/customer/estimation.html
{% extends "bootstrap/base.html" %}

{% block title %}
Report
{% endblock %}
{% block styles %}
{{super()}}
<style type="text/css">
  .footer-storm {
   position:fixed;
   left:0px;
   bottom:0px;
   height:10%;
   width:100%;
   background: black;
   color: white;
   font: italic bold 12px/15px Georgia, serif;
}

   .footer-content{
   	position: absolute;
  	bottom: 0;
  	left: 0;
   }
</style>
{% endblock %}

{%block content%}
<script type="text/javascript" src="{{ url_for('static', filename='storm.js') }}"></script>
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">storm-risk</a>
        </div>
        <div class="navbar-header">
          <a class="navbar-brand" href="{{ url_for('mod_auth.dashboardcustomer') }}">New Appraisal</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('mod_auth.logout') }}">Log Out</a></li>
           

          </ul>
        </div>
      </div>
</nav>
<div class="container-fluid">
<div class="row" style="margin-top: 50px">
	<div class="col-md-6" style="text-align: center;">
	<p>Estimated ($ Loss)</p>
	{{ div_placeholder }}
	<p> Wind Speed mph </p>
	</div>
	<div class="col-md-6">
		<h4> storm-risk estimated your original house value on ${{value}}<br> based on your location and other details provided</h4>
		<table class="table table-striped">
		    <thead>
		      <tr>
		        <th>Category</th>
		        <th>Estimated Damage</th>
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td>Tropical Storm</td>
		        <td>${{dollar_damage[0]}}</td>
		      </tr>
		      <tr>
		        <td>Category I</td>
		        <td>${{dollar_damage[1]}}</td>
		      </tr>
		      <tr>
		        <td>Category II</td>

		        <td>${{dollar_damage[2]}}</td>
		      </tr>
		      <tr>
		        <td>Category III</td>
		        <td>${{dollar_damage[3]}}</td>
		      </tr>
		      <tr>
		        <td>Category IV</td>
		        <td>${{dollar_damage[4]}}</td>
		      </tr>
		      <tr>
		        <td>Category V</td>
		        <td>${{dollar_damage[5]}}</td>
		      </tr>
		    </tbody>
  		</table>

	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<table class="table table-striped">
		    <thead>
		      <tr>
		        <th>Category</th>
		        <th>Description</th>
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td><img src="{{ url_for('static', filename='one.png') }}" width="50px" height="45px" alt=""></td>
		        <td>Rating of one means no damage or very minor damage for hurricane category 4,<br>
		         No broken windows, minimal roof damage, very limited water penetration.</td>
		      </tr>
		      <tr>
		        <td><img src="{{ url_for('static', filename='two.png') }}" width="50px" height="45px" alt=""></td>
		        <td>Rating of two means minor damage for hurricane of category 3 or 4. Moderate roof cover loss, walls and roof renovations like painting or patching repair may be required.</td>
		      </tr>
		      <tr>
		        <td><img src="{{ url_for('static', filename='three.png') }}" width="50px" height="45px" alt=""></td>
		        <td>Rating of three means moderate or severe damage for hurricane of category 2 or 3. <br>
		        Major roof cover damage with resulting damage to the interior of the building from the water.</td>
		      </tr>
		      <tr>
		        <td><img src="{{ url_for('static', filename='four.png') }}" width="50px" height="45px" alt=""></td>
		        <td>Rating of four means severe damage or destruction for hurricane of category 2 or 3. Major roof cover loss, complete roof failure possibe.</td>
		      </tr>
		      
		    </tbody>
  	</table>
	</div>
	<div class="col-md-6" style="text-align: center; font: 25">
		<h2>Storm-Risk Rating: </h2>
		{% if rate == 1 %}
		<img src="{{ url_for('static', filename='one.png') }}" width="50px" height="45px" alt="">
		<h3><b>Congratulation! Your home received category 1 in storm-risk scale, which is the highest possible rating. <br> You are hurricane proof!!! </b></h3>
		{% elif rate == 2 %}
		<img src="{{ url_for('static', filename='two.png') }}" width="50px" height="45px" alt="">
		<h3><b>Almost there. Your home can sustain quite serious hurricane event, but a small investment can make it hurricane proof and undestructible.</b></h3>
		{% elif rate == 3 %}
		<img src="{{ url_for('static', filename='three.png') }}" width="50px" height="45px" alt="">
		<h3><b>Danger! You received category 3 in storm-risk rating. Your is vulnerable for severe damages during even Category 2 hurricane. Consider an investment in your safety.</b></h3>
		{% else %}
		<img src="{{ url_for('static', filename='four.png') }}" width="50px" height="45px" alt="">
		<h3><b>Unfortunately, your home did not pass our test. Consider a serious investment in window protection, roof renovation or roof to wall connections.</b></h3>
		{% endif %}
	</div>
</div>
<div class="row">
	<div class="col-md-6">
	
	</div>
	<div class="col-md-6" >
		<div class="btn-group-vertical" style="width: 100%" >
  		<a href="{{ url_for('mod_auth.mitigation') }}">
  		<button type="button" class="btn btn-primary btn-lg btn-block" style="margin-top: 20px">Mitigate Damage
  		</button></a>
		<button type="button" class="btn btn-success btn-lg btn-block" value="Print this page" onclick="printPage()" style="margin-top: 20px">Save Report</button>
		</div>

	</div>
</div>
</div>
</div>
{% endblock %}

app/templates/customer/estimation_mit.html
{% extends "bootstrap/base.html" %}

{% block title %}
Dashboard Customer
{% endblock %}

{% block styles %}
{{super()}}
<style type="text/css">
  .footer-storm {
   position:fixed;
   left:0px;
   bottom:0px;
   height:10%;
   width:100%;
   background: black;
   color: white;
   font: italic bold 12px/15px Georgia, serif;
}

   .footer-content{
   	position: absolute;
  	bottom: 0;
  	left: 0;
   }
</style>
{% endblock %}

{%block content%}
<script type="text/javascript" src="{{ url_for('static', filename='storm.js') }}"></script>

<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">storm-risk</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('mod_auth.logout') }}">Log Out</a></li>
           

          </ul>
        </div>
      </div>
</nav>
<div class="container-fluid" >
<div class="row" style="margin-top: 60px">
	<div class="col-md-6" style="text-align: center;">
	<p>Initial Estimate ($ Loss)</p>
	{{ div_placeholder }}
	<p> Wind Speed mph </p>
	</div>
	<div class="col-md-6" style="text-align: center;">
	<p> After Mitigation ($ Loss)</p>
	{{ div_placeholder_mit }}
	<p> Wind Speed mph </p>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<h4> storm-risk estimated your original house value on ${{value}}<br> based on your location and other details provided</h4>
		<table class="table table-striped">
		    <thead>
		      <tr>
		        <th>Category</th>
		        <th>Before Mitigation</th>
		        <th>After Mitigation</th>
		        <th> Saved </th>
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td>Tropical Storm</td>
		        <td>${{dollar_damage[0]}}</td>
		        <td>${{dollar_damage_mit[0]}}</td>
		        <td>${{dollar_damage[0] - dollar_damage_mit[0] }}</td>
		      </tr>
		      <tr>
		        <td>Category I</td>
		        <td>${{dollar_damage[1]}}</td>
		        <td>${{dollar_damage_mit[1]}}</td>
		        <td>${{dollar_damage[1] - dollar_damage_mit[1] }}</td>
		      </tr>
		      <tr>
		        <td>Category II</td>
		        <td>${{dollar_damage[2]}}</td>
		        <td>${{dollar_damage_mit[2]}}</td>
		        <td>${{dollar_damage[2] - dollar_damage_mit[2] }}</td>
		      </tr>
		      <tr>
		        <td>Category III</td>
		        <td>${{dollar_damage[3]}}</td>
		        <td>${{dollar_damage_mit[3]}}</td>
		        <td>${{dollar_damage[3] - dollar_damage_mit[3] }}</td>
		      </tr>
		      <tr>
		        <td>Category IV</td>
		        <td>${{dollar_damage[4]}}</td>
		        <td>${{dollar_damage_mit[4]}}</td>
		        <td>${{dollar_damage[4] - dollar_damage_mit[4] }}</td>
		      </tr>
		      <tr>
		        <td>Category V</td>
		        <td>${{dollar_damage[5]}}</td>
		        <td>${{dollar_damage_mit[5]}}</td>
		        <td>${{dollar_damage[5] - dollar_damage_mit[5] }}</td>
		      </tr>
		    </tbody>
  		</table>

	</div>
	<div class="col-md-6" style="text-align: center; font: 25">
		<h2>Your New Storm-Risk Rating: </h2>
		{% if rate == 1 %}
		<img src="{{ url_for('static', filename='one.png') }}" width="50px" height="45px" alt="">
		<h3><b>Congratulation! Your home received category 1 in storm-risk scale, which is the highest possible rating. <br> You are hurricane proof!!! </b></h3>
		{% elif rate == 2 %}
		<img src="{{ url_for('static', filename='two.png') }}" width="50px" height="45px" alt="">
		<h3><b>Almost there. Your home can sustain quite serious hurricane event, but a small investment can make it hurricane proof and undestructible.</b></h3>
		{% elif rate == 3 %}
		<img src="{{ url_for('static', filename='three.png') }}" width="50px" height="45px" alt="">
		<h3><b>Danger! You received category 3 in storm-risk rating. Your is vulnerable for severe damages during even Category 2 hurricane. Consider an investment in your safety.</b></h3>
		{% else %}
		<img src="{{ url_for('static', filename='four.png') }}" width="50px" height="45px" alt="">
		<h3><b>Unfortunately, your home did not pass our test. Consider a serious investment in window protection, roof renovation or roof to wall connections.</b></h3>
		{% endif %}
	</div>
</div>
<div class="row" style="margin-bottom: : 40px">
	<div class="col-md-6">
	<table class="table table-striped">
		    <thead>
		      <tr>
		        <th>Category</th>
		        <th>Description</th>
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td><img src="{{ url_for('static', filename='one.png') }}" width="50px" height="45px" alt=""></td>
		        <td>Rating of one means no damage or very minor damage for hurricane category 4,<br>
		         No broken windows, minimal roof damage, very limited water penetration.</td>
		      </tr>
		      <tr>
		        <td><img src="{{ url_for('static', filename='two.png') }}" width="50px" height="45px" alt=""></td>
		        <td>Rating of two means minor damage for hurricane of category 3 or 4. Moderate roof cover loss, walls and roof renovations like painting or patching repair may be required.</td>
		      </tr>
		      <tr>
		        <td><img src="{{ url_for('static', filename='three.png') }}" width="50px" height="45px" alt=""></td>
		        <td>Rating of three means moderate or severe damage for hurricane of category 2 or 3. <br>
		        Major roof cover damage with resulting damage to the interior of the building from the water.</td>
		      </tr>
		      <tr>
		        <td><img src="{{ url_for('static', filename='four.png') }}" width="50px" height="45px" alt=""></td>
		        <td>Rating of four means severe damage or destruction for hurricane of category 2 or 3. Major roof cover loss, complete roof failure possibe.</td>
		      </tr>
		    </tbody>
  	</table>
	</div>
	<div class="col-md-6" >
		<div class="btn-group-vertical" style="width: 100%" >
  		<a href="{{ url_for('mod_auth.dashboardcustomer') }}"><button type="button" class="btn btn-primary btn-lg btn-block" style="margin-top: 20px">New Appraisal</button></a>
		<button type="button" class="btn btn-success btn-lg btn-block" value="Print this page" onclick="printPage()" style="margin-top: 20px">Save Report</button>
		</div>

	</div>

</div>
</div>

{% endblock %}

app/templates/customer/mitigate.html
<!-- Author Daniel Bis -->
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}
Dashboard
{% endblock %}

{% block styles %}
{{super()}}
<style type="text/css">
  .footer-storm {
   position:fixed;
   left:0px;
   bottom:0px;
   height:10%;
   width:100%;
   background: black;
   color: white;
   font: italic bold 12px/15px Georgia, serif;
}

   .footer-content{
   	position: absolute;
  	bottom: 0;
  	left: 0;
   }
  .logo {
    position: relative;,
    top: 0;
    left: 0;
  }
  body {
    background-color: white; 
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    color: #fff !important;
    font-size: 16px;

  }

</style>
{% endblock %}



{% block content %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">storm-risk</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('mod_auth.logout') }}">Log Out</a></li>
           

          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid" style="color: black;">
      <div class="row" style="margin-top: 60px">
        <div class="col-md-6" style = "text-align: center; margin-top: 20px background-color: black">
          
          <div class="row" style="margin-top: 40px">
          <div class="col-md-4" style="text-align: left;"> 
              <img class = "logo" src="{{ url_for('static', filename='logo.jpg') }}" width="100%" height="100%">
          </div>
          <div class="col-md-8" style="margin-top: 60px;">
            <p > We are here to prevent, not respond. Don't let hurricane suprise you, check your potential loses, find vulnerabilities and fix them. <br> Protect your home and family.</p>
          </div>
          </div>
      </div>


        <div class="col-md-6" style = "text-align: left; background: #fff margin-left: 0" >
            <form class="form-appraisal" method="POST", action="/auth/mitigation">
            <h2 class="form-appraisal-heading">Select Improvements</h2>
            {{ form.hidden_tag() }}
            {{ wtf.form_field(form.window_protection) }}
            {{ wtf.form_field(form.type_of_windows) }}
            {{ wtf.form_field(form.roof_wall_connection) }}
            {{ wtf.form_field(form.type_of_roof_cover) }}
            {{ wtf.form_field(form.type_of_roof_sheathing) }}
            <button class="btn btn-lg btn-primary btn-block" type="submit">Upgrade</button>
            </form>
        </div>
        
    </div>
    
    </div>



<footer class="footer-storm">
<p class="footer-content">&copy; PolHack <br> Created by Daniel Bis and Grzegorz Kakareko as a HackFSU 2018 project.<br> danbisoffice@gmail.com, g.kakareko@gmail.com <br>
</p>
</footer>
{% endblock %}